### ISSUE TITLE
SendJSONError missing Content-Type header

### ISSUE THREAD

**Issue by jhsc** [go-fuego/fuego#87]
**To Reproduce**
I noticed that when trying to return json error, the `Content-Type` returns as `text/plain`, when it should be `application/json`

1. Add simple json endpoint 
```go
fuego.GetStd(server, "/json", func(w http.ResponseWriter, r *http.Request) {
   fuego.SendJSONError(w, fuego.ErrUnauthorized)
})
```
2. Curl endpoint
```
$ curl -v --request GET \
  --url http://localhost:8080/json \
  --header 'Accept: application/json'
```
3. Somehow content type is text?
```
*   Trying [::1]:8080...
* Connected to localhost (::1) port 8080
> GET /json HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.4.0
> Accept: application/json
>
< HTTP/1.1 500 Internal Server Error
< Date: Thu, 21 Mar 2024 17:39:05 GMT
< Content-Length: 3
< Content-Type: text/plain; charset=utf-8
<
{}
```

**Expected behavior**
SendJSONError should set "Content-Type" to "application/json".

**Framework version (please check if it happens with the last Fuego version before posting):**
Tried on both 0.12.0 and latest commit b01f3b407f07029deaea4f983af6220ec2301cb7

**Go version (please check if it happens with the last Go version before posting):**
1.22.1

**Additional context**
I tried to add debug breakpoints and I see that the response header gets those values, but somehow the final response seems to be missing headers?

**Comment by EwenQuim** [comment]
Hi @jhsc and thank you for the report!

Everything is now fixed in v0.13!

**Comment by jhsc** [comment]
Thank you so much, such a cool project!!!!

**Comment by EwenQuim** [comment]
Just so you know, it is better to use the structs errors, like `UnauthorizedError{}` instead of `ErrUnauthorized`. We will deprecate `ErrUnauthorized` in a few releases

**Comment by jhsc** [comment]
@EwenQuim I think I found the possible root of the issue, it seems that `WriteHeader` has to be called after all the headers have been set. I'm still getting the wrong `Content-Type` and after reading a bit I found this [stackoverflow](https://stackoverflow.com/questions/70507501/content-type-of-http-response-changes-when-using-external-clients-but-is-correct) similar issue.

**Comment by EwenQuim** [comment]
Wow that was tricky, thanks for pointing out this issue @jhsc!

From now on, we'll be using `w.Result().Header` instead of the faulty `w.Header()`in tests.

Issue has been solved in v0.13.1
